# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 10
    - name: Set up OpenJDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Setup Maven
      uses: aahmed-se/setup-maven@v3
    - name: Build with Maven
      run: mvn -B clean test verify package --file pom.xml
